### ISSUE TITLE
app/ and db/ dirs missing 

### ISSUE THREAD

**Issue by ojnc** [Leoooob/cap_hello_world#1]
app/ content for UI frontends goes here

db/  your domain models and data go here

Please provide a sample if possible

Regards
Jayanta

**Comment by Leoooob** [comment]
Hi Jayanta, there is no app or db content in this repository. If you want a proper example of a full-stack CAP project, have a look at this repo: https://github.com/Leoooob/bookshop

**Comment by ojnc** [comment]
Thanks Leoooob

Though a beautiful page came at http://localhost:4004'
nothing really worked; I tinkered a lot but to no avail

Tried [https://github.com/SAP-samples/cloud-cap-samples](https://github.com/SAP-samples/cloud-cap-samples)
Here too minor hiccups
But **npm run start** OR **npm run fiori work** fine

Everything worked fine

Regards & Thanks
Jayanta
